# Generated by Django 5.2.4 on 2025-08-01 04:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Imagen')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
            ],
        ),
    ]
