# Generated by Django 5.2.4 on 2025-08-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
